-- Curated exercise catalogue.
--
-- Repeatable: ids are derived from the slug, so re-running this file (or applying it to a new
-- environment) always yields the same canonical exercise ids. Updating a row here renames it
-- everywhere without touching anyone's history, because history references the id.
-- Genuinely different variations (barbell vs dumbbell vs machine, different movements) are
-- separate exercises and are never merged.

insert into public.exercises (id, slug, name, primary_muscle, equipment, tracking_mode, aliases)
select md5('splitmate.catalogue:' || v.slug)::uuid, v.slug, v.name, v.muscle, v.equipment, v.mode, v.aliases
from (values
  ('barbell-bench-press', 'Barbell Bench Press', 'chest', 'barbell', 'weight_reps', array['bench press', 'flat bench']::text[]),
  ('incline-barbell-bench-press', 'Incline Barbell Bench Press', 'chest', 'barbell', 'weight_reps', array['incline press', 'incline bench']::text[]),
  ('decline-barbell-bench-press', 'Decline Barbell Bench Press', 'chest', 'barbell', 'weight_reps', array['decline bench']::text[]),
  ('dumbbell-bench-press', 'Dumbbell Bench Press', 'chest', 'dumbbell', 'weight_reps', array['db bench', 'flat dumbbell press']::text[]),
  ('incline-dumbbell-press', 'Incline Dumbbell Press', 'chest', 'dumbbell', 'weight_reps', array['incline db press', 'incline press']::text[]),
  ('machine-chest-press', 'Machine Chest Press', 'chest', 'machine', 'weight_reps', array['chest press']::text[]),
  ('incline-machine-chest-press', 'Incline Machine Chest Press', 'chest', 'machine', 'weight_reps', array['incline press', 'incline chest press']::text[]),
  ('smith-machine-bench-press', 'Smith Machine Bench Press', 'chest', 'smith_machine', 'weight_reps', array['smith bench']::text[]),
  ('smith-machine-incline-press', 'Smith Machine Incline Press', 'chest', 'smith_machine', 'weight_reps', array['smith incline', 'incline press']::text[]),
  ('cable-fly', 'Cable Fly', 'chest', 'cable', 'weight_reps', array['cable crossover', 'chest fly']::text[]),
  ('low-to-high-cable-fly', 'Low-to-High Cable Fly', 'chest', 'cable', 'weight_reps', array['upper chest fly']::text[]),
  ('dumbbell-fly', 'Dumbbell Fly', 'chest', 'dumbbell', 'weight_reps', array['db fly']::text[]),
  ('pec-deck', 'Pec Deck', 'chest', 'machine', 'weight_reps', array['machine fly', 'butterfly']::text[]),
  ('push-up', 'Push-Up', 'chest', 'bodyweight', 'bodyweight_reps', array['press up', 'pushup']::text[]),
  ('dip', 'Dip', 'chest', 'bodyweight', 'added_weight_reps', array['weighted dip', 'dips', 'parallel bar dip']::text[]),
  ('conventional-deadlift', 'Deadlift', 'back', 'barbell', 'weight_reps', array['conventional deadlift']::text[]),
  ('trap-bar-deadlift', 'Trap Bar Deadlift', 'back', 'trap_bar', 'weight_reps', array['hex bar deadlift']::text[]),
  ('rack-pull', 'Rack Pull', 'back', 'barbell', 'weight_reps', array[]::text[]),
  ('barbell-row', 'Barbell Row', 'back', 'barbell', 'weight_reps', array['bent over row', 'bb row']::text[]),
  ('pendlay-row', 'Pendlay Row', 'back', 'barbell', 'weight_reps', array[]::text[]),
  ('one-arm-dumbbell-row', 'One-Arm Dumbbell Row', 'back', 'dumbbell', 'weight_reps', array['db row', 'single arm row']::text[]),
  ('seated-cable-row', 'Seated Cable Row', 'back', 'cable', 'weight_reps', array['cable row', 'low row']::text[]),
  ('chest-supported-machine-row', 'Chest-Supported Machine Row', 'back', 'machine', 'weight_reps', array['machine row']::text[]),
  ('t-bar-row', 'T-Bar Row', 'back', 'barbell', 'weight_reps', array['landmine row']::text[]),
  ('lat-pulldown', 'Lat Pulldown', 'back', 'cable', 'weight_reps', array['pulldown', 'lat pull down']::text[]),
  ('close-grip-lat-pulldown', 'Close-Grip Lat Pulldown', 'back', 'cable', 'weight_reps', array['v-bar pulldown']::text[]),
  ('single-arm-cable-pulldown', 'Single-Arm Cable Pulldown', 'back', 'cable', 'weight_reps', array[]::text[]),
  ('machine-lat-pulldown', 'Machine Lat Pulldown', 'back', 'machine', 'weight_reps', array['plate loaded pulldown']::text[]),
  ('straight-arm-pulldown', 'Straight-Arm Pulldown', 'back', 'cable', 'weight_reps', array['lat pushdown']::text[]),
  ('pull-up', 'Pull-Up', 'back', 'bodyweight', 'added_weight_reps', array['weighted pull-up', 'pullup']::text[]),
  ('chin-up', 'Chin-Up', 'back', 'bodyweight', 'added_weight_reps', array['weighted chin-up', 'chinup']::text[]),
  ('back-extension', 'Back Extension', 'back', 'bodyweight', 'added_weight_reps', array['hyperextension']::text[]),
  ('barbell-shrug', 'Barbell Shrug', 'back', 'barbell', 'weight_reps', array['shrug', 'traps']::text[]),
  ('dumbbell-shrug', 'Dumbbell Shrug', 'back', 'dumbbell', 'weight_reps', array['shrug']::text[]),
  ('barbell-overhead-press', 'Barbell Overhead Press', 'shoulders', 'barbell', 'weight_reps', array['ohp', 'military press', 'shoulder press']::text[]),
  ('seated-dumbbell-shoulder-press', 'Seated Dumbbell Shoulder Press', 'shoulders', 'dumbbell', 'weight_reps', array['db shoulder press', 'shoulder press']::text[]),
  ('machine-shoulder-press', 'Machine Shoulder Press', 'shoulders', 'machine', 'weight_reps', array['shoulder press']::text[]),
  ('arnold-press', 'Arnold Press', 'shoulders', 'dumbbell', 'weight_reps', array[]::text[]),
  ('dumbbell-lateral-raise', 'Dumbbell Lateral Raise', 'shoulders', 'dumbbell', 'weight_reps', array['side raise', 'lateral raise']::text[]),
  ('cable-lateral-raise', 'Cable Lateral Raise', 'shoulders', 'cable', 'weight_reps', array['lateral raise']::text[]),
  ('machine-lateral-raise', 'Machine Lateral Raise', 'shoulders', 'machine', 'weight_reps', array['lateral raise']::text[]),
  ('dumbbell-rear-delt-fly', 'Dumbbell Rear Delt Fly', 'shoulders', 'dumbbell', 'weight_reps', array['reverse fly', 'rear delt raise']::text[]),
  ('reverse-pec-deck', 'Reverse Pec Deck', 'shoulders', 'machine', 'weight_reps', array['rear delt machine', 'reverse fly']::text[]),
  ('face-pull', 'Face Pull', 'shoulders', 'cable', 'weight_reps', array[]::text[]),
  ('upright-row', 'Upright Row', 'shoulders', 'barbell', 'weight_reps', array[]::text[]),
  ('barbell-curl', 'Barbell Curl', 'biceps', 'barbell', 'weight_reps', array['bb curl']::text[]),
  ('ez-bar-curl', 'EZ-Bar Curl', 'biceps', 'ez_bar', 'weight_reps', array['ez curl']::text[]),
  ('dumbbell-curl', 'Dumbbell Curl', 'biceps', 'dumbbell', 'weight_reps', array['db curl', 'bicep curl']::text[]),
  ('hammer-curl', 'Hammer Curl', 'biceps', 'dumbbell', 'weight_reps', array[]::text[]),
  ('incline-dumbbell-curl', 'Incline Dumbbell Curl', 'biceps', 'dumbbell', 'weight_reps', array[]::text[]),
  ('preacher-curl', 'EZ-Bar Preacher Curl', 'biceps', 'ez_bar', 'weight_reps', array['preacher curl']::text[]),
  ('machine-preacher-curl', 'Machine Preacher Curl', 'biceps', 'machine', 'weight_reps', array['preacher curl']::text[]),
  ('cable-curl', 'Cable Curl', 'biceps', 'cable', 'weight_reps', array[]::text[]),
  ('triceps-pushdown', 'Triceps Pushdown', 'triceps', 'cable', 'weight_reps', array['rope pushdown', 'tricep pushdown']::text[]),
  ('overhead-cable-triceps-extension', 'Overhead Cable Triceps Extension', 'triceps', 'cable', 'weight_reps', array['overhead extension']::text[]),
  ('skull-crusher', 'EZ-Bar Skull Crusher', 'triceps', 'ez_bar', 'weight_reps', array['lying triceps extension', 'skullcrusher']::text[]),
  ('close-grip-bench-press', 'Close-Grip Bench Press', 'triceps', 'barbell', 'weight_reps', array['cgbp']::text[]),
  ('dumbbell-overhead-triceps-extension', 'Dumbbell Overhead Triceps Extension', 'triceps', 'dumbbell', 'weight_reps', array[]::text[]),
  ('machine-triceps-extension', 'Machine Triceps Extension', 'triceps', 'machine', 'weight_reps', array[]::text[]),
  ('back-squat', 'Barbell Back Squat', 'quads', 'barbell', 'weight_reps', array['squat', 'back squat']::text[]),
  ('front-squat', 'Barbell Front Squat', 'quads', 'barbell', 'weight_reps', array['front squat']::text[]),
  ('hack-squat', 'Hack Squat', 'quads', 'machine', 'weight_reps', array[]::text[]),
  ('leg-press', 'Leg Press', 'quads', 'machine', 'weight_reps', array[]::text[]),
  ('smith-machine-squat', 'Smith Machine Squat', 'quads', 'smith_machine', 'weight_reps', array[]::text[]),
  ('goblet-squat', 'Goblet Squat', 'quads', 'dumbbell', 'weight_reps', array[]::text[]),
  ('bulgarian-split-squat', 'Dumbbell Bulgarian Split Squat', 'quads', 'dumbbell', 'weight_reps', array['bss', 'split squat']::text[]),
  ('walking-lunge', 'Dumbbell Walking Lunge', 'quads', 'dumbbell', 'weight_reps', array['lunge']::text[]),
  ('step-up', 'Dumbbell Step-Up', 'quads', 'dumbbell', 'weight_reps', array[]::text[]),
  ('leg-extension', 'Leg Extension', 'quads', 'machine', 'weight_reps', array['quad extension']::text[]),
  ('barbell-romanian-deadlift', 'Barbell Romanian Deadlift', 'hamstrings', 'barbell', 'weight_reps', array['rdl', 'romanian deadlift']::text[]),
  ('dumbbell-romanian-deadlift', 'Dumbbell Romanian Deadlift', 'hamstrings', 'dumbbell', 'weight_reps', array['db rdl']::text[]),
  ('lying-leg-curl', 'Lying Leg Curl', 'hamstrings', 'machine', 'weight_reps', array['hamstring curl']::text[]),
  ('seated-leg-curl', 'Seated Leg Curl', 'hamstrings', 'machine', 'weight_reps', array['hamstring curl']::text[]),
  ('good-morning', 'Good Morning', 'hamstrings', 'barbell', 'weight_reps', array[]::text[]),
  ('barbell-hip-thrust', 'Barbell Hip Thrust', 'glutes', 'barbell', 'weight_reps', array['hip thrust']::text[]),
  ('machine-hip-thrust', 'Machine Hip Thrust', 'glutes', 'machine', 'weight_reps', array['hip thrust']::text[]),
  ('glute-bridge', 'Glute Bridge', 'glutes', 'bodyweight', 'added_weight_reps', array[]::text[]),
  ('cable-glute-kickback', 'Cable Glute Kickback', 'glutes', 'cable', 'weight_reps', array['kickback']::text[]),
  ('hip-abduction', 'Hip Abduction Machine', 'glutes', 'machine', 'weight_reps', array['abductor']::text[]),
  ('hip-adduction', 'Hip Adduction Machine', 'adductors', 'machine', 'weight_reps', array['adductor']::text[]),
  ('standing-calf-raise', 'Standing Calf Raise', 'calves', 'machine', 'weight_reps', array['calf raise']::text[]),
  ('seated-calf-raise', 'Seated Calf Raise', 'calves', 'machine', 'weight_reps', array['calf raise']::text[]),
  ('leg-press-calf-raise', 'Leg Press Calf Raise', 'calves', 'machine', 'weight_reps', array['calf press']::text[]),
  ('cable-crunch', 'Cable Crunch', 'core', 'cable', 'weight_reps', array['kneeling crunch']::text[]),
  ('hanging-leg-raise', 'Hanging Leg Raise', 'core', 'bodyweight', 'bodyweight_reps', array['leg raise']::text[]),
  ('ab-wheel-rollout', 'Ab Wheel Rollout', 'core', 'other', 'bodyweight_reps', array['ab roller']::text[]),
  ('decline-sit-up', 'Decline Sit-Up', 'core', 'bodyweight', 'added_weight_reps', array['sit up']::text[]),
  ('dumbbell-wrist-curl', 'Dumbbell Wrist Curl', 'forearms', 'dumbbell', 'weight_reps', array['wrist curl']::text[]),
  ('kettlebell-swing', 'Kettlebell Swing', 'full_body', 'kettlebell', 'weight_reps', array['kb swing']::text[])
) as v (slug, name, muscle, equipment, mode, aliases)
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  primary_muscle = excluded.primary_muscle,
  equipment = excluded.equipment,
  tracking_mode = excluded.tracking_mode,
  aliases = excluded.aliases,
  updated_at = now();
